SELECT USER
FROM DUAL;
--==>> SCOTT


--○ 테이블 생성
CREATE TABLE TBL_MEMBERLIST
( ID        VARCHAR2(30)
, PW        VARCHAR2(20) NOT NULL
, NAME      VARCHAR2(50) NOT NULL
, TEL       VARCHAR2(50) NOT NULL
, EMAIL     VARCHAR2(100) NOT NULL
, CONSTRAINT MEMBERLIST_ID_PK PRIMARY KEY(ID)
, CONSTRAINT MEMBERLIST_TEL_UK UNIQUE(TEL)
); 
--==>> Table TBL_MEMBERLIST이(가) 생성되었습니다.


--○ 전체 리스트 조회
SELECT ID, PW, NAME, TEL, EMAIL FROM TBL_MEMBERLIST
;


--○ 데이터 입력
INSERT INTO TBL_MEMBERLIST(ID, PW, NAME, TEL, EMAIL) VALUES('admin', 'admin1234', '관리자', '010-1234-5678', 'admin@test.com')
;

SELECT ID FROM TBL_MEMBERLIST WHERE ID = 'admin'
;

commit;
